[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wbindgen = [ "naia-socket-shared/wbindgen" ]

[dependencies]
naia-socket-shared = "0.8"
